/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'weather_scraper.py': [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python/usr/bin/python: No such file or directory
/bin/sh: /env/bin/python: No such file or directory
/bin/sh: /env/bin/python: No such file or directory
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "weather_scraper.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
Traceback (most recent call last):
  File "weather_scraper.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
Traceback (most recent call last):
  File "weather_scraper.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
90
6
writing
90
6
writing
90
6
writing
90
6
writing
90
6
writing
90
6
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
67.5
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
4
writing
90
3
writing
90
3
writing
90
3
writing
90
3
writing
135
3
writing
135
3
writing
135
2
writing
135
2
writing
135
2
writing
135
2
writing
135
2
writing
135
2
writing
225
4
writing
225
4
writing
225
4
writing
225
4
writing
225
4
writing
225
4
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
3
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
6
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
247.5
8
writing
270
9
writing
270
9
writing
270
9
writing
270
9
writing
270
9
writing
270
9
writing
270
11
writing
270
11
writing
270
11
writing
270
11
writing
270
11
writing
270
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
292.5
11
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
292.5
16
writing
270
18
writing
270
18
writing
270
18
writing
270
18
writing
270
18
writing
270
18
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
14
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
16
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
15
writing
270
12
writing
270
12
writing
315
12
writing
315
12
writing
315
12
writing
315
12
writing
315
13
writing
315
13
writing
315
13
writing
315
13
writing
315
13
writing
315
13
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
10
writing
327.5
8
writing
0
8
writing
0
8
writing
0
8
writing
0
8
writing
0
8
writing
0
8
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
22.5
9
writing
45
8
writing
45
8
writing
45
8
writing
45
8
writing
45
8
writing
45
8
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
7
writing
45
5
writing
45
5
writing
45
5
writing
45
5
writing
45
5
writing
45
5
writing
45
6
writing
45
6
writing
45
6
writing
45
6
writing
45
6
writing
45
6
writing
90
5
writing
90
5
writing
90
5
writing
90
5
writing
90
5
writing
90
5
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
135
7
writing
112.5
6
writing
112.5
6
writing
112.5
6
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
157.5
7
writing
135
10
writing
135
10
writing
135
10
writing
135
10
writing
135
10
writing
135
10
writing
157.5
11
writing
157.5
11
writing
Traceback (most recent call last):
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x107385cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='weather.bm', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weather_scraper.py", line 11, in <module>
    page = requests.get(URL)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Users/oliverriihiluoma/Documents/personal/projects/weather_scraper/env/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='weather.bm', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
157.5
11
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
14
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
13
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
15
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
157.5
17
writing
180
15
writing
180
15
writing
180
15
writing
180
15
writing
180
15
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
11
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
12
writing
180
13
writing
180
13
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
180
14
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
15
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
14
writing
202.5
13
writing
225
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
202.5
13
writing
225
16
writing
202.5
15
writing
202.5
15
writing
202.5
14
writing
225
13
writing
225
13
writing
225
13
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
19
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
202.5
21
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
20
writing
225
19
writing
225
19
writing
225
19
writing
225
19
writing
225
19
writing
225
18
writing
225
18
writing
225
16
writing
225
16
writing
225
16
writing
247.5
18
writing
225
17
writing
225
17
writing
225
17
writing
